### PR TITLE
Breaking: clusterSubscription config/secret no longer needed

### PR DESCRIPTION
**Pull request by dalehille**
The clustersubscription configmap/secret are no longer required for ClusterSubscription.   This change removes `--rd-api `and `--rd-tags` from install options since they were only used to generate the clustersubscription configmap

### CODE REVIEW

**Comment by alewitt2** [comment]
@dalehille do these changes also require that `razee-identity` configmap and secret exist?

**Comment by dalehille** [comment]
> @dalehille do these changes also require that `razee-identity` configmap and secret exist?

yes

**Comment by alewitt2** [comment]
ok, then before we merge this, we need to update it to create the `razee-identity` configmap and secret

**Comment by alewitt2** [comment]
i can do that on your branch

**Comment by alewitt2** [comment]
there were some extra changes needed in order to make sure all config was applied. So i opened a new PR for you to review @dalehille https://github.com/razee-io/razeedeploy-delta/pull/113

**Pull request closed without merging**
